version: "3"

services:
    db:
        container_name: dvrpdb_db
        image: postgres:12
        volumes:
            - postgres_data:/var/lib/postgresql/data
        environment:
            - POSTGRES_USER=hello_django
            - POSTGRES_PASSWORD=hello_django
            - POSTGRES_DB=hello_django_dev
        ports: 
            - "5432:5432"

volumes:
    postgres_data: