version: "3"

services:
  db:
    container_name: dvrpdb_db
    image: postgres:12
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=hello_django
      - POSTGRES_PASSWORD=hello_django
      - POSTGRES_DB=hello_django_dev


  backend:
    container_name: dvrpdb_backend
    build: ./backend

    volumes:
      - ./backend/:/usr/src/backend
      - django-static:/usr/src/backend/static
      - django-media:/usr/src/backend/media
    restart: unless-stopped
    stdin_open: true
    tty: true
    env_file:
      - ./backend/.env.dev
    ports:
      - "8000:8000"
    depends_on:
      - db

  redis:
    image: redis:2.8
    ports:
      - "6379:6379"

  # nginx:
  #   container_name: nginx_drpv
  #   build:
  #     context: .
  #     dockerfile: nginx/Dockerfile
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - backend
  #   links:
  #     - backend
  #   tty: true
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
  #     - django-static:/usr/src/app/static

volumes:
  postgres_data:
  django-static:
  django-media:
