# Generated by Django 3.0.3 on 2020-07-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_messages', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='startmessage',
            name='recipient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Recipient', to='users.Profile', verbose_name='Listener'),
        ),
        migrations.AddField(
            model_name='startmessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Sender', to='users.Profile', verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='replymessage',
            name='reply_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='u_messages.StartMessage', verbose_name='Dialog'),
        ),
        migrations.AddField(
            model_name='replymessage',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile', verbose_name='Answerer'),
        ),
    ]
