# Generated by Django 3.0.3 on 2020-07-14 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200713_1115'),
        ('u_messages', '0002_auto_20200709_0552'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StartMessage',
            new_name='Dialog',
        ),
        migrations.RenameModel(
            old_name='ReplyMessage',
            new_name='Reply',
        ),
    ]
