# Generated by Django 3.0.3 on 2020-07-14 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('u_messages', '0003_auto_20200714_1602'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reply',
            old_name='reply_for',
            new_name='dialog',
        ),
    ]
