# Generated by Django 3.0.3 on 2020-07-01 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('post', '0001_initial'),
        ('users', '0004_auto_20200626_1526'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50, verbose_name='Type of instance')),
                ('_id', models.IntegerField(verbose_name='Instance ID')),
                ('by_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_of_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_user', to='users.Profile')),
                ('watcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_user', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionForPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_of_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_post', to='post.Post')),
                ('watcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_post', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='SubscriptionForCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_of_observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_category', to='post.Category')),
                ('watcher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_category', to='users.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actions', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='u_notification.Actions')),
                ('to_users', models.ManyToManyField(to='users.Profile')),
            ],
        ),
    ]
