# Generated by Django 3.0.3 on 2020-07-03 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=500)),
                ('type', models.CharField(max_length=50, verbose_name='Type of instance')),
                ('post_id', models.PositiveIntegerField(verbose_name='Post ID')),
                ('comment_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Comment id')),
            ],
            options={
                'verbose_name': 'Action',
                'verbose_name_plural': 'Actions',
            },
        ),
        migrations.CreateModel(
            name='Notifications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionForCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'subscription for category',
                'verbose_name_plural': 'subscriptions for categories',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionForPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'subscription for post',
                'verbose_name_plural': 'subscriptions for posts',
            },
        ),
        migrations.CreateModel(
            name='SubscriptionForUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'subscription for user',
                'verbose_name_plural': 'subscriptions for users',
            },
        ),
    ]
