# Generated by Django 3.0.3 on 2020-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('u_notification', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actions',
            name='_id',
            field=models.PositiveIntegerField(verbose_name='Instance ID'),
        ),
    ]
