# Generated by Django 3.0.3 on 2020-07-03 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('u_notification', '0001_initial'),
        ('post', '0002_auto_20200703_1344'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionforuser',
            name='object_of_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_user', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='subscriptionforuser',
            name='watcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_user', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='subscriptionforpost',
            name='object_of_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_post', to='post.Post'),
        ),
        migrations.AddField(
            model_name='subscriptionforpost',
            name='watcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_post', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='subscriptionforcategory',
            name='object_of_observation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observation_for_category', to='post.Category'),
        ),
        migrations.AddField(
            model_name='subscriptionforcategory',
            name='watcher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='watch_for_category', to='users.Profile'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='actions',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='u_notification.Actions'),
        ),
        migrations.AddField(
            model_name='notifications',
            name='to_users',
            field=models.ManyToManyField(to='users.Profile'),
        ),
        migrations.AddField(
            model_name='actions',
            name='by_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile'),
        ),
    ]
