# Generated by Django 3.0.3 on 2020-07-03 12:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('u_notification', '0002_auto_20200703_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='actions',
            name='date_add',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
