export default {
  POSTS: "POSTS",
  POSTDETAIL: "POSTDETAIL",
  CREATEDNEWACC: "CREATEDNEWACC",
  ERRREGISTERMAIL: "ERRREGISTERMAIL",
  ERRREGISTERPASS: "ERRREGISTERPASS",
  ISAUTH: "ISAUTH",
  ERRLOGIN: "ERRLOGIN",
  OWNPROFILE: "OWNPROFILE",
  PROFILE: "PROFILE",
  USER: "USER",
  DIALOGS: "DIALOGS",
  DIALOGDETAIL: "DIALOGDETAIL",
};
