export default {
  POSTS: "POSTS",
  POSTDETAIL: "POSTDETAIL",
  CREATEDNEWACC:"CREATEDNEWACC",
  ERRREGISTERMAIL:"ERRREGISTERMAIL",
  ERRREGISTERPASS:"ERRREGISTERPASS",
  ISAUTH: "ISAUTH",
  ERRLOGIN:"ERRLOGIN",
  PROFILE: "PROFILE",
};
