# Generated by Django 3.0.3 on 2020-06-26 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200626_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, max_length=150, unique=True, verbose_name='Username'),
        ),
    ]
