# Generated by Django 3.0.3 on 2020-07-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200626_1526'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new_notification',
            field=models.IntegerField(default=0, null=True, verbose_name='Number of new notifications'),
        ),
    ]
