# Generated by Django 3.0.3 on 2020-07-01 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_new_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='new_notification',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='Number of new notifications'),
        ),
    ]
